base_url = "https://sujalhansda.github.io"
title = "Sujal Hansda"


compile_sass = true

highlight_code = true

build_search_index = false

check_external_links = true

taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]

[extra]
show_word_count = true
show_reading_time = true

date_format = "%a %b %e, %Y"

home = "home"

sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "about", link = "/about" },
    { text = "resume", link = "/resume.pdf" }
]

sam_bottom_menu = true

[extra.sam_footer]
text = "Out Of Time"

[extra.social]
mail = "mailto:sujal.hansda.ph@gmail.com"
github = "https://github.com/SujalHansda"